import type { IconType } from 'react-icons';
import {
  FaStore, FaUtensils, FaSpa, FaGem, FaGamepad, FaFilm, FaTshirt, FaLaptop, FaHeart, FaGift, FaCouch, FaUsers,
  FaUniversity, FaShoppingBag, FaShieldAlt, FaParking, FaLaptopCode, FaGraduationCap, FaDumbbell, FaDraftingCompass,
  FaTicketAlt, FaPizzaSlice, FaHamburger, FaFemale, FaCoffee, FaChild, FaTags, FaNewspaper, FaLightbulb, FaHistory,
  FaBuilding, FaBookOpen, FaAward, FaWheelchair, FaVrCardboard, FaVolumeUp, FaTv, FaStar, FaLeaf, FaInfoCircle,
  FaHandshake, FaGlobe, FaChargingStation, FaMapMarkerAlt, FaClock, FaPhoneAlt, FaEnvelope, FaCompass, FaCalendarAlt,
  FaWifi, FaBaby, FaRestroom, FaArrowsAltV, FaCar, FaMoneyBillWave, FaFirstAid, FaMusic, FaCamera, FaGlassCheers,
  FaIceCream, FaBirthdayCake, FaMale, FaTools, FaMobileAlt, FaBriefcase, FaHotel, FaLock, FaSmile, FaTag,
} from 'react-icons/fa';

/**
 * Icons the CMS can reference by name. Content stores the key (e.g. "utensils"),
 * so staff pick from a list and the site never breaks on an unknown value.
 */
export const ICONS: Record<string, { label: string; icon: IconType }> = {
  store: { label: 'Store', icon: FaStore },
  'shopping-bag': { label: 'Shopping bag', icon: FaShoppingBag },
  tag: { label: 'Tag', icon: FaTag },
  tags: { label: 'Tags', icon: FaTags },
  tshirt: { label: 'T-shirt', icon: FaTshirt },
  female: { label: 'Woman', icon: FaFemale },
  male: { label: 'Man', icon: FaMale },
  child: { label: 'Child', icon: FaChild },
  baby: { label: 'Baby', icon: FaBaby },
  heart: { label: 'Heart', icon: FaHeart },
  gem: { label: 'Gem', icon: FaGem },
  spa: { label: 'Spa / beauty', icon: FaSpa },
  laptop: { label: 'Laptop', icon: FaLaptop },
  mobile: { label: 'Mobile phone', icon: FaMobileAlt },
  couch: { label: 'Home / furniture', icon: FaCouch },
  gift: { label: 'Gift', icon: FaGift },
  utensils: { label: 'Restaurant', icon: FaUtensils },
  pizza: { label: 'Pizza', icon: FaPizzaSlice },
  burger: { label: 'Burger', icon: FaHamburger },
  coffee: { label: 'Coffee', icon: FaCoffee },
  'ice-cream': { label: 'Ice cream', icon: FaIceCream },
  cake: { label: 'Cake', icon: FaBirthdayCake },
  cheers: { label: 'Drinks', icon: FaGlassCheers },
  film: { label: 'Cinema', icon: FaFilm },
  ticket: { label: 'Ticket', icon: FaTicketAlt },
  gamepad: { label: 'Games', icon: FaGamepad },
  vr: { label: 'VR', icon: FaVrCardboard },
  music: { label: 'Music', icon: FaMusic },
  camera: { label: 'Camera', icon: FaCamera },
  tv: { label: 'Screen', icon: FaTv },
  sound: { label: 'Sound', icon: FaVolumeUp },
  bank: { label: 'Bank', icon: FaUniversity },
  money: { label: 'Money / ATM', icon: FaMoneyBillWave },
  education: { label: 'Education', icon: FaGraduationCap },
  book: { label: 'Book', icon: FaBookOpen },
  code: { label: 'IT / software', icon: FaLaptopCode },
  dumbbell: { label: 'Fitness', icon: FaDumbbell },
  drafting: { label: 'Engineering', icon: FaDraftingCompass },
  briefcase: { label: 'Office', icon: FaBriefcase },
  tools: { label: 'Tools / repair', icon: FaTools },
  hotel: { label: 'Hotel', icon: FaHotel },
  building: { label: 'Building', icon: FaBuilding },
  parking: { label: 'Parking', icon: FaParking },
  car: { label: 'Car', icon: FaCar },
  charging: { label: 'EV charging', icon: FaChargingStation },
  wheelchair: { label: 'Accessibility', icon: FaWheelchair },
  restroom: { label: 'Restroom', icon: FaRestroom },
  elevator: { label: 'Elevator', icon: FaArrowsAltV },
  wifi: { label: 'Wi-Fi', icon: FaWifi },
  'first-aid': { label: 'First aid', icon: FaFirstAid },
  shield: { label: 'Security', icon: FaShieldAlt },
  lock: { label: 'Lock', icon: FaLock },
  users: { label: 'People', icon: FaUsers },
  handshake: { label: 'Handshake', icon: FaHandshake },
  smile: { label: 'Smile', icon: FaSmile },
  star: { label: 'Star', icon: FaStar },
  award: { label: 'Award', icon: FaAward },
  leaf: { label: 'Leaf', icon: FaLeaf },
  lightbulb: { label: 'Idea', icon: FaLightbulb },
  history: { label: 'History', icon: FaHistory },
  newspaper: { label: 'News', icon: FaNewspaper },
  globe: { label: 'Globe', icon: FaGlobe },
  info: { label: 'Info', icon: FaInfoCircle },
  pin: { label: 'Map pin', icon: FaMapMarkerAlt },
  compass: { label: 'Compass', icon: FaCompass },
  clock: { label: 'Clock', icon: FaClock },
  phone: { label: 'Phone', icon: FaPhoneAlt },
  email: { label: 'Email', icon: FaEnvelope },
  calendar: { label: 'Calendar', icon: FaCalendarAlt },
};

export const ICON_OPTIONS = Object.entries(ICONS).map(([value, { label }]) => ({ value, label }));

/** Renders a CMS icon by key, falling back to a neutral icon for unknown keys. */
export function CmsIcon({ name, className, fallback = 'store' }: { name?: string; className?: string; fallback?: string }) {
  const Icon = (name && ICONS[name]?.icon) || ICONS[fallback]?.icon || FaStore;
  return <Icon className={className} aria-hidden="true" />;
}
