import { defineBlock, type BlockDef } from '../block';
import type { Field } from '../fields';

const t = (key: string, label: string, help?: string): Field => ({ key, label, type: 'text', help });
const ta = (key: string, label: string, help?: string): Field => ({ key, label, type: 'textarea', help });

export const latestPageBlock = defineBlock({
  key: 'latest-page',
  group: "What's on page",
  label: "What's on page copy",
  description: 'Headings, tab names, button labels, empty messages and the event RSVP form on the Latest page.',
  page: '/latest',
  fields: [
    t('title', 'Page title'),
    ta('subtitle', 'Page intro'),
    t('badge', 'Badge above the title'),
    t('breadcrumbParent', 'Breadcrumb: section name'),
    t('breadcrumbCurrent', 'Breadcrumb: this page'),
    t('tabAll', 'Tab: everything'),
    t('tabBlogs', 'Tab: blogs'),
    t('tabEvents', 'Tab: events'),
    t('tabOffers', 'Tab: offers'),

    t('blogsEyebrow', 'Blogs: small label'),
    t('blogsHeading', 'Blogs: heading'),
    ta('blogsIntro', 'Blogs: intro'),
    t('blogsFeaturedBadge', 'Blogs: badge on the first story'),
    t('blogsReadTime', 'Blogs: reading time on the first story', 'Leave empty to hide.'),
    t('blogsReadFull', 'Blogs: button on the first story'),
    t('blogsCardLabel', 'Blogs: small label on each card'),
    t('blogsByPrefix', 'Blogs: word before the author name'),
    t('blogsReadMore', 'Blogs: card link'),
    t('blogsEmpty', 'Blogs: message when there are no stories'),

    t('eventsEyebrow', 'Events: small label'),
    t('eventsHeading', 'Events: heading'),
    ta('eventsIntro', 'Events: intro'),
    t('eventsDetails', 'Events: details link'),
    t('eventsEmpty', 'Events: message when there are no events'),
    t('modalDateLabel', 'Event popup: date label'),
    t('modalVenueLabel', 'Event popup: venue label'),
    t('modalClose', 'Event popup: close button'),

    { key: 'rsvpEnabled', label: 'Allow RSVP on events', type: 'toggle', help: 'When on, every event has an RSVP button. Replies arrive in the Inbox.' },
    t('rsvpButton', 'RSVP: button on each event'),
    t('rsvpModalButton', 'RSVP: button in the event popup'),
    t('rsvpDoneButton', 'RSVP: button after replying'),
    t('rsvpFormTitle', 'RSVP form: heading'),
    ta('rsvpFormIntro', 'RSVP form: intro'),
    t('rsvpNameLabel', 'RSVP form: name label'),
    t('rsvpEmailLabel', 'RSVP form: email label'),
    t('rsvpPhoneLabel', 'RSVP form: phone label'),
    t('rsvpGuestsLabel', 'RSVP form: guests label'),
    t('rsvpNoteLabel', 'RSVP form: note label'),
    t('rsvpSubmit', 'RSVP form: send button'),
    t('rsvpSending', 'RSVP form: while sending'),
    t('rsvpContactError', 'RSVP form: message when email and phone are both empty'),
    t('rsvpSuccessTitle', 'RSVP form: thank-you heading'),
    ta('rsvpSuccessText', 'RSVP form: thank-you message'),

    t('offersEyebrow', 'Offers: small label'),
    t('offersHeading', 'Offers: heading'),
    ta('offersIntro', 'Offers: intro'),
    t('offersPromoLabel', 'Offers: promo code label'),
    t('offersCopy', 'Offers: copy button'),
    t('offersCopied', 'Offers: after copying'),
    t('offersStoreLink', 'Offers: store link'),
    t('offersEmpty', 'Offers: message when there are no offers'),
  ],
  defaults: {
    title: 'Latest',
    subtitle: 'Stay updated with our newest editorial stories, vibrant mall events, and exclusive seasonal discounts at Pokhara Trade Mall.',
    badge: "WHAT'S ON",
    breadcrumbParent: "What's On",
    breadcrumbCurrent: 'Latest',
    tabAll: 'All Updates',
    tabBlogs: 'Blogs & Stories',
    tabEvents: 'Events & Happenings',
    tabOffers: 'Latest Offers',

    blogsEyebrow: 'Stories & Articles',
    blogsHeading: 'Latest Blogs & Insights',
    blogsIntro: 'Discover lifestyle tips, dining recommendations, and insider shopping guides curated by our editorial team.',
    blogsFeaturedBadge: 'Featured Story',
    blogsReadTime: '4 min read',
    blogsReadFull: 'Read Full Story',
    blogsCardLabel: 'Editorial',
    blogsByPrefix: 'By',
    blogsReadMore: 'Read More',
    blogsEmpty: 'New stories are on the way. Check back soon.',

    eventsEyebrow: 'Calendar of Events',
    eventsHeading: 'Upcoming Events & Happenings',
    eventsIntro: 'Live concerts, cultural food fests, movie premiere nights, and family gaming tournaments at Pokhara Trade Mall.',
    eventsDetails: 'View Details',
    eventsEmpty: 'No events are scheduled right now. New happenings are announced here first.',
    modalDateLabel: 'Date & Time',
    modalVenueLabel: 'Venue Location',
    modalClose: 'Close',

    rsvpEnabled: true,
    rsvpButton: 'Save Event',
    rsvpModalButton: 'Save to My Schedule',
    rsvpDoneButton: 'Added Reminder!',
    rsvpFormTitle: 'Reserve your spot',
    rsvpFormIntro: 'Leave your details and our events team will confirm your place.',
    rsvpNameLabel: 'Your name',
    rsvpEmailLabel: 'Email',
    rsvpPhoneLabel: 'Phone',
    rsvpGuestsLabel: 'Guests',
    rsvpNoteLabel: 'Note (optional)',
    rsvpSubmit: 'Send RSVP',
    rsvpSending: 'Sending…',
    rsvpContactError: 'Please add an email or phone number so we can reach you.',
    rsvpSuccessTitle: "You're on the list!",
    rsvpSuccessText: "Thanks for your RSVP. We'll be in touch with the details.",

    offersEyebrow: 'Deals & Vouchers',
    offersHeading: 'Latest Offers & Promotions',
    offersIntro: 'Claim exclusive coupon codes and special store discounts across retail, dining, and cinema at Pokhara Trade Mall.',
    offersPromoLabel: 'Promo Code',
    offersCopy: 'Copy',
    offersCopied: 'Copied!',
    offersStoreLink: 'Explore Store',
    offersEmpty: 'No offers are running right now. Fresh deals land here often.',
  },
});

export const blogPageBlock = defineBlock({
  key: 'blog-page',
  group: "What's on page",
  label: 'Blog article page copy',
  description: 'Labels around every blog article.',
  page: '/latest#blogs',
  fields: [
    ta('subtitle', 'Intro under the article title'),
    t('badge', 'Badge above the title'),
    t('breadcrumbParent', 'Breadcrumb: section name'),
    t('backLink', 'Back link'),
    t('sideLabel', 'Label next to the back link'),
    t('tagLabel', 'Tag on the article'),
    t('authorLabel', 'Author shown on the article'),
    t('shareLabel', 'Share: label'),
    t('shareButton', 'Share: button'),
    t('shareCopied', 'Share: message after copying the link'),
    t('browseButton', 'Button at the end of the article'),
    t('loading', 'Loading message'),
    t('notFoundTitle', 'Missing article: heading'),
    ta('notFoundText', 'Missing article: message'),
    t('notFoundButton', 'Missing article: button'),
  ],
  defaults: {
    subtitle: 'Editorial features, events, lifestyle news, and shopping guides from Pokhara Trade Mall.',
    badge: 'Editorial Article',
    breadcrumbParent: 'Latest & Stories',
    backLink: 'Back to All Stories',
    sideLabel: 'Pokhara Trade Mall Editorial',
    tagLabel: 'Featured Story',
    authorLabel: 'PTM Editorial Desk',
    shareLabel: 'Share:',
    shareButton: 'Share Story',
    shareCopied: 'Link copied to clipboard!',
    browseButton: "Browse What's On",
    loading: 'Loading article...',
    notFoundTitle: 'Article Not Found',
    notFoundText: 'The article or story you are looking for is unavailable or has been moved.',
    notFoundButton: 'Back to Latest Stories',
  },
});

export const latestBlocks: BlockDef<any>[] = [latestPageBlock, blogPageBlock];
